services:
  - type: web
    name: numbott-telethon
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: CHECK_CHANNELS
        sync: false
      - key: JOIN_URLS
        sync: false
      - key: LZT_API_KEY
        sync: false
      - key: LZT_MARGIN
        value: "25.0"
      - key: PYTHON_VERSION
        value: 3.10.12
